-- SELECT PRODUCT_ID, PRODUCT_NAME FROM Products;
-- SELECT * FROM PRODUCTS;
-- SELECT DISTINCT SUPPLIER_ID,CATEGORY_ID FROM PRODUCTS;
--SELECT [SUPPLIER ID] FROM PRODUCTS
--SELECT * FROM PRODUCTS WHERE CATEGORY_ID=1;
--SELECT * FROM PRODUCTS WHERE PRODUCT_NAME='Chai';
-- SELECT * FROM PRODUCTS WHERE CATEGORY_ID BETWEEN 1 AND 2;
-- SELECT * FROM PRODUCTS WHERE CATEGORY_ID >= 1 AND CATEGORY_ID <=2;
--SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE '%ai';
--SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE 'ai%';
--SELECT * FROM PRODUCTS WHERE PRODUCT_NAME LIKE '%ai%';
--SELECT * FROM PRODUCTS WHERE CATEGORY_ID IN (1,3,5);
--SELECT * FROM PRODUCTS WHERE CATEGORY_ID = 1 OR CATEGORY_ID = 3 OR CATEGORY_ID = 5;
--SELECT * FROM PRODUCTS WHERE (CATEGORY_ID = 1 OR CATEGORY_ID = 2) AND SUPPLIER_ID < 20;
--SELECT * FROM PRODUCTS WHERE NOT (CATEGORY_ID = 5 OR CATEGORY_ID = 1);
--SELECT * FROM PRODUCTS WHERE NOT CATEGORY_ID IN (1,5);
-- SELECT * FROM PRODUCTS ORDER BY CATEGORY_ID DESC, SUPPLIER_ID DESC;
/*
CREATE TABLE PRODUCTS2
(
    PRODUCT_ID NUMBER(9) NOT NULL,
    PRODUCT_NAME VARCHAR2(40 BYTE) NOT NULL
);
*/
/*
INSERT INTO PRODUCTS2 (PRODUCT_ID, PRODUCT_NAME)
SELECT PRODUCT_ID, PRODUCT_NAME FROM PRODUCTS WHERE PRODUCTS.CATEGORY_ID = 5;
*/
-- SELECT * FROM PRODUCTS2;
--SELECT * FROM SUPPLIERS WHERE REGION IS NOT NULL;
--UPDATE PRODUCTS SET UNITS_IN_STOCK=UNITS_IN_STOCK-1, UNIT_PRICE=25 WHERE PRODUCT_ID IN (1,2,3);
--DELETE FROM PRODUCTS WHERE UNITS_IN_STOCK < 10;
/*
SELECT * FROM (SELECT * FROM PRODUCTS ORDER BY UNITS_IN_STOCK DESC) Step1
WHERE ROWNUM <= 10;

SELECT * FROM PRODUCTS WHERE ROWNUM <= 10 ORDER BY UNITS_IN_STOCK DESC;
*/
--SELECT MAX(UNITS_IN_STOCK) AS MAX_UNITS_IN_STOCK
--FROM PRODUCTS WHERE CATEGORY_ID = 3;
--SELECT PRODUCT_ID AS ID, PRODUCT_NAME AS Product FROM PRODUCTS;
/*
SELECT * FROM
(SELECT PRODUCT_NAME,UNITS_IN_STOCK FROM PRODUCTS WHERE CATEGORY_ID = 3 ORDER BY UNITS_IN_STOCK DESC) Step1
WHERE ROWNUM <= 1;
*/
/*
SELECT * FROM PRODUCTS WHERE UNITS_IN_STOCK = (SELECT MAX(UNITS_IN_STOCK) AS MAX_UNITS_IN_STOCK
FROM PRODUCTS WHERE CATEGORY_ID = 3);
*/
/*
SELECT CATEGORIES.CATEGORY_NAME, QUANTITY FROM
(SELECT CATEGORY_ID, COUNT(*) AS Quantity FROM PRODUCTS
GROUP BY CATEGORY_ID) Step1
INNER JOIN CATEGORIES ON Step1.CATEGORY_ID = CATEGORIES.CATEGORY_ID
ORDER BY QUANTITY DESC;
*/
/*
CREATE TABLE TABLE_2
(
  COL int
);

INSERT INTO TABLE_2(COL) VALUES (3);
INSERT INTO TABLE_2(COL) VALUES (4);
INSERT INTO TABLE_2(COL) VALUES (5);
INSERT INTO TABLE_2(COL) VALUES (6);
*/
/*
SELECT TABLE_1.COL AS COL1,TABLE_2.COL AS COL2
FROM TABLE_1 FULL OUTER JOIN TABLE_2 ON (TABLE_2.COL = TABLE_1.COL AND TABLE_2.COL > 0);
-- WHERE TABLE_2.COL IS NULL;
*/

--SELECT PRODUCT_NAME, UNITS_IN_STOCK+UNITS_ON_ORDER AS TOTAL_UNITS FROM PRODUCTS;



