SELECT * FROM
(SELECT CUSTOMERS.COMPANY_NAME, ROUND(TOTAL_PAID/ORDER_COUNT,1) AS AVERAGE_PER_ORDER FROM
(SELECT CUSTOMER_ID, COUNT(*) AS ORDER_COUNT FROM ORDERS
GROUP BY CUSTOMER_ID
ORDER BY ORDER_COUNT DESC) STEP1
INNER JOIN
(SELECT ORDERS.CUSTOMER_ID,SUM(TOTAL_PAID) AS TOTAL_PAID FROM ORDERS
INNER JOIN (SELECT ORDER_ID, SUM(UNIT_PRICE * QUANTITY * (1-DISCOUNT)) AS TOTAL_PAID
FROM ORDER_DETAILS
GROUP BY ORDER_ID) STEP2 ON ORDERS.ORDER_ID=STEP2.ORDER_ID
GROUP BY ORDERS.CUSTOMER_ID
) STEP3
ON STEP1.CUSTOMER_ID = STEP3.CUSTOMER_ID
INNER JOIN CUSTOMERS
ON STEP1.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
ORDER BY AVERAGE_PER_ORDER DESC)
WHERE ROWNUM = 1;